spring:
  data:
    mongodb:
      uri: mongodb://localhost/Ygwguser
  thymeleaf:
    cache: false


  devtools:
    livereload:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /ygwg-admin


